version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    command: >
      postgres -c 'timezone=America/Sao_Paulo'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_service
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    networks:
      - app-network
    environment:
      - DATABASE_URL = ${DATABASE_URL}
      - JWT_SECRET = ${JWT_SECRET}
      - JWT_EXPIRATION = ${JWT_EXPIRATION}

volumes:
  postgres_data:
  redisdata:

networks:
  app-network:
    driver: bridge
